"""Smoke tests for M5 (frame_extractor).

Tests use synthetic video generated by ffmpeg itself, so no real YouTube download needed.
"""

import subprocess
import shutil
import tempfile
from pathlib import Path

from videodigest.transcriber import Segment, merge_segments
from videodigest.frame_extractor import (
    Frame,
    extract_frames,
    extract_frames_at_timestamps,
    _phash,
    _is_duplicate,
    _select_candidates,
)

TMP = Path(tempfile.mkdtemp(prefix="videodigest_m5_"))


def make_test_video(path: Path, duration: int = 30) -> Path:
    cmd = [
        "ffmpeg", "-y",
        "-f", "lavfi",
        "-i", f"testsrc=duration={duration}:size=320x240:rate=1",
        "-c:v", "libx264", "-pix_fmt", "yuv420p",
        str(path),
    ]
    r = subprocess.run(cmd, capture_output=True)
    assert r.returncode == 0 and path.exists(), f"ffmpeg failed: {r.stderr.decode()}"
    return path


def _make_solid(size=128):
    from PIL import Image
    return Image.new("RGB", (size, size), (128, 128, 128))


def _make_checkerboard(size=128):
    import numpy as np
    from PIL import Image
    arr = np.zeros((size, size, 3), dtype=np.uint8)
    arr[::8, :] = 255
    arr[:, ::8] = 255
    return Image.fromarray(arr)


def test_dedup_logic():
    print("=== M5: dedup logic ===")
    import imagehash

    h1 = imagehash.phash(_make_solid())
    h2 = imagehash.phash(_make_solid())
    assert _is_duplicate(h2, [h1], threshold=8)

    h3 = imagehash.phash(_make_checkerboard())
    assert not _is_duplicate(h3, [h1], threshold=8)

    print("  duplicate detection: OK")
    print("  different image passthrough: OK")


def test_candidate_selection():
    print("\n=== M5: candidate selection ===")
    segs = [Segment(start=i, end=i + 1, text=f"seg {i}") for i in range(100)]

    indices = _select_candidates(segs, max_candidates=10)
    assert len(indices) == 10
    assert indices[0] == 0
    assert all(0 <= i < 100 for i in indices)
    print(f"  100 segments → 10 candidates: {indices}")

    small = [Segment(start=i, end=i + 1, text="x") for i in range(5)]
    assert _select_candidates(small, max_candidates=10) == [0, 1, 2, 3, 4]
    print("  5 segments → 5 candidates (no sampling): OK")


def test_extract_frames():
    print("\n=== M5: extract_frames ===")
    video = make_test_video(TMP / "test.mp4", duration=30)
    out_dir = TMP / "frames"

    segments = [
        Segment(start=0, end=10, text="intro"),
        Segment(start=10, end=20, text="middle"),
        Segment(start=20, end=30, text="end"),
    ]

    frames = extract_frames(video, segments, out_dir, max_frames=6, dedup_threshold=4)

    print(f"  Extracted {len(frames)} unique frames")
    for f in frames:
        print(f"  {f.timestamp_str}  segment={f.segment_index}  {f.path.name}  {f.path.stat().st_size // 1024}KB")
        assert f.path.exists()

    assert len(frames) >= 1
    assert all(isinstance(f, Frame) for f in frames)
    assert frames == sorted(frames, key=lambda x: x.timestamp)


def test_extract_frames_at_timestamps():
    print("\n=== M5: extract_frames_at_timestamps ===")
    video = TMP / "test.mp4"
    out_dir = TMP / "frames_ts"

    frames = extract_frames_at_timestamps(video, timestamps=[5.0, 15.0, 25.0], output_dir=out_dir)
    print(f"  Extracted {len(frames)} frames at explicit timestamps")
    for f in frames:
        print(f"  {f.timestamp_str}  {f.path.name}")
    assert len(frames) >= 1


if __name__ == "__main__":
    ffmpeg = shutil.which("ffmpeg")
    if not ffmpeg:
        print("SKIP: ffmpeg not found. Install with: brew install ffmpeg")
        raise SystemExit(0)

    try:
        import imagehash
        from PIL import Image
    except ImportError:
        print("SKIP: imagehash/Pillow not installed. Run: pip3 install imagehash Pillow")
        raise SystemExit(0)

    test_dedup_logic()
    test_candidate_selection()
    test_extract_frames()
    test_extract_frames_at_timestamps()

    shutil.rmtree(TMP, ignore_errors=True)
    print("\nAll M5 checks passed.")
